version: "3.9"
services:
  graphite:
    container_name: graphite
    image: graphiteapp/graphite-statsd
    restart: "always"
    ports:
      - "2004:2004"
    networks:
      - internal
    volumes:
      - ./graphite-conf:/opt/graphite/conf
      - graphite-storage:/opt/graphite/storage

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - internal
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel

networks:
  internal:

volumes:
  graphite-storage:
  grafana-storage: