{
 "title": "Buoy Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Buoys", "query": "buoy_monitor.*" }
  ]
 },
 "panels": [
  {
   "title": "Debug",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "buoy_monitor.$Buoys.station_keeping.lat"
    },
    {
     "target": "buoy_monitor.$Buoys.station_keeping.lon"
    }
   ]
  },
  {
   "title": "Map",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "alias(buoy_monitor.*.station_keeping.lat, 'lat')"
    },
    {
     "target": "alias(buoy_monitor.*.station_keeping.lon, 'lon')"
    },
    {
     "target": "alias(buoy_monitor.*.fluorescence.sensor_0, 'metric')"
    }
   ]
  },
  {
   "title": "Fluorescence Readings",
   "type": "graph",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "buoy_monitor.$Buoys.fluorescence.*"
    }
   ]
  },
  {
   "title": "Station Keeping",
   "type": "graph",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "buoy_monitor.$Buoys.station_keeping.*"
    }
   ]
  }
 ]
}